name = "nvim"

bashrc = [
    "alias so='source .venv/bin/activate'",
    "alias ex='export $(cat .env)'",
    "export EDITOR='nvim'",
    "alias vi='nvim .'",
]

[packages]
pacman = [
    "neovim",
    "tree-sitter-cli",
    "wl-clipboard",
    "ripgrep",
    "fd",
    "asciidoctor",
]
