name = "arch"

bashrc = [
    "export CONFIG_REPO=git@github.com:KaiPenazzi/configs.git",
    "export CONFIG_BRANCH=work",
    "alias vi='nvim .'",
    "alias pro='cd ~/code/provisioner'",
    "export PATH=\"$HOME/.cargo/bin:$PATH\"",
]

[packages]
pacman = [
    "bluez",
    "bluez-utils",
    "chafa",
    "dosfstools",
    "fastfetch",
    "git",
    "htop",
    "keepassxc",
    "less",
    "network-manager-applet",
    "pipewire",
    "pipewire-alsa",
    "pipewire-pulse",
    "tcpdump",
    "tlp",
    "tlp-rdw",
    "torbrowser-launcher",
    "unzip",
    "webkit2gtk",
    "zip",
]

aur = [
    "aura",
    "zen-browser-bin",
    "ttf-jetbrains-mono-nerd",
    "network-manager-sstp",
]
